insert into backend_location (id, name) values (0, E'Canada');
insert into backend_areacode (id, code, country_id) values (0, '1', 0);
insert into backend_location (id, name) values (1, E'Afghanistan');
insert into backend_areacode (id, code, country_id) values (1, '93', 1);
insert into backend_location (id, name) values (2, E'Albania');
insert into backend_areacode (id, code, country_id) values (2, '355', 2);
insert into backend_location (id, name) values (3, E'Algeria');
insert into backend_areacode (id, code, country_id) values (3, '213', 3);
insert into backend_location (id, name) values (4, E'AmericanSamoa');
insert into backend_areacode (id, code, country_id) values (4, '1684', 4);
insert into backend_location (id, name) values (5, E'Andorra');
insert into backend_areacode (id, code, country_id) values (5, '376', 5);
insert into backend_location (id, name) values (6, E'Angola');
insert into backend_areacode (id, code, country_id) values (6, '244', 6);
insert into backend_location (id, name) values (7, E'Anguilla');
insert into backend_areacode (id, code, country_id) values (7, '1264', 7);
insert into backend_location (id, name) values (8, E'Antarctica');
insert into backend_areacode (id, code, country_id) values (8, '672', 8);
insert into backend_location (id, name) values (9, E'Antigua and Barbuda');
insert into backend_areacode (id, code, country_id) values (9, '1268', 9);
insert into backend_location (id, name) values (10, E'Argentina');
insert into backend_areacode (id, code, country_id) values (10, '54', 10);
insert into backend_location (id, name) values (11, E'Armenia');
insert into backend_areacode (id, code, country_id) values (11, '374', 11);
insert into backend_location (id, name) values (12, E'Aruba');
insert into backend_areacode (id, code, country_id) values (12, '297', 12);
insert into backend_location (id, name) values (13, E'Australia');
insert into backend_areacode (id, code, country_id) values (13, '61', 13);
insert into backend_location (id, name) values (14, E'Austria');
insert into backend_areacode (id, code, country_id) values (14, '43', 14);
insert into backend_location (id, name) values (15, E'Azerbaijan');
insert into backend_areacode (id, code, country_id) values (15, '994', 15);
insert into backend_location (id, name) values (16, E'Bahamas');
insert into backend_areacode (id, code, country_id) values (16, '1242', 16);
insert into backend_location (id, name) values (17, E'Bahrain');
insert into backend_areacode (id, code, country_id) values (17, '973', 17);
insert into backend_location (id, name) values (18, E'Bangladesh');
insert into backend_areacode (id, code, country_id) values (18, '880', 18);
insert into backend_location (id, name) values (19, E'Barbados');
insert into backend_areacode (id, code, country_id) values (19, '1246', 19);
insert into backend_location (id, name) values (20, E'Belarus');
insert into backend_areacode (id, code, country_id) values (20, '375', 20);
insert into backend_location (id, name) values (21, E'Belgium');
insert into backend_areacode (id, code, country_id) values (21, '32', 21);
insert into backend_location (id, name) values (22, E'Belize');
insert into backend_areacode (id, code, country_id) values (22, '501', 22);
insert into backend_location (id, name) values (23, E'Benin');
insert into backend_areacode (id, code, country_id) values (23, '229', 23);
insert into backend_location (id, name) values (24, E'Bermuda');
insert into backend_areacode (id, code, country_id) values (24, '1441', 24);
insert into backend_location (id, name) values (25, E'Bhutan');
insert into backend_areacode (id, code, country_id) values (25, '975', 25);
insert into backend_location (id, name) values (26, E'Bolivia, Plurinational State of');
insert into backend_areacode (id, code, country_id) values (26, '591', 26);
insert into backend_location (id, name) values (27, E'Bosnia and Herzegovina');
insert into backend_areacode (id, code, country_id) values (27, '387', 27);
insert into backend_location (id, name) values (28, E'Botswana');
insert into backend_areacode (id, code, country_id) values (28, '267', 28);
insert into backend_location (id, name) values (29, E'Brazil');
insert into backend_areacode (id, code, country_id) values (29, '55', 29);
insert into backend_location (id, name) values (30, E'British Indian Ocean Territory');
insert into backend_areacode (id, code, country_id) values (30, '246', 30);
insert into backend_location (id, name) values (31, E'Brunei Darussalam');
insert into backend_areacode (id, code, country_id) values (31, '673', 31);
insert into backend_location (id, name) values (32, E'Bulgaria');
insert into backend_areacode (id, code, country_id) values (32, '359', 32);
insert into backend_location (id, name) values (33, E'Burkina Faso');
insert into backend_areacode (id, code, country_id) values (33, '226', 33);
insert into backend_location (id, name) values (34, E'Burundi');
insert into backend_areacode (id, code, country_id) values (34, '257', 34);
insert into backend_location (id, name) values (35, E'Cambodia');
insert into backend_areacode (id, code, country_id) values (35, '855', 35);
insert into backend_location (id, name) values (36, E'Cameroon');
insert into backend_areacode (id, code, country_id) values (36, '237', 36);
insert into backend_location (id, name) values (37, E'Cape Verde');
insert into backend_areacode (id, code, country_id) values (37, '238', 37);
insert into backend_location (id, name) values (38, E'Cayman Islands');
insert into backend_areacode (id, code, country_id) values (38, '345', 38);
insert into backend_location (id, name) values (39, E'Central African Republic');
insert into backend_areacode (id, code, country_id) values (39, '236', 39);
insert into backend_location (id, name) values (40, E'Chad');
insert into backend_areacode (id, code, country_id) values (40, '235', 40);
insert into backend_location (id, name) values (41, E'Chile');
insert into backend_areacode (id, code, country_id) values (41, '56', 41);
insert into backend_location (id, name) values (42, E'China');
insert into backend_areacode (id, code, country_id) values (42, '86', 42);
insert into backend_location (id, name) values (43, E'Christmas Island');
insert into backend_areacode (id, code, country_id) values (43, '61', 43);
insert into backend_location (id, name) values (44, E'Cocos (Keeling) Islands');
insert into backend_areacode (id, code, country_id) values (44, '61', 44);
insert into backend_location (id, name) values (45, E'Colombia');
insert into backend_areacode (id, code, country_id) values (45, '57', 45);
insert into backend_location (id, name) values (46, E'Comoros');
insert into backend_areacode (id, code, country_id) values (46, '269', 46);
insert into backend_location (id, name) values (47, E'Congo');
insert into backend_areacode (id, code, country_id) values (47, '242', 47);
insert into backend_location (id, name) values (48, E'Congo, The Democratic Republic of the');
insert into backend_areacode (id, code, country_id) values (48, '243', 48);
insert into backend_location (id, name) values (49, E'Cook Islands');
insert into backend_areacode (id, code, country_id) values (49, '682', 49);
insert into backend_location (id, name) values (50, E'Costa Rica');
insert into backend_areacode (id, code, country_id) values (50, '506', 50);
insert into backend_location (id, name) values (51, E'Cote d\'Ivoire');
insert into backend_areacode (id, code, country_id) values (51, '225', 51);
insert into backend_location (id, name) values (52, E'Croatia');
insert into backend_areacode (id, code, country_id) values (52, '385', 52);
insert into backend_location (id, name) values (53, E'Cuba');
insert into backend_areacode (id, code, country_id) values (53, '53', 53);
insert into backend_location (id, name) values (54, E'Cyprus');
insert into backend_areacode (id, code, country_id) values (54, '357', 54);
insert into backend_location (id, name) values (55, E'Czech Republic');
insert into backend_areacode (id, code, country_id) values (55, '420', 55);
insert into backend_location (id, name) values (56, E'Curaçao');
insert into backend_areacode (id, code, country_id) values (56, '599', 56);
insert into backend_location (id, name) values (57, E'Canary Islands');
insert into backend_areacode (id, code, country_id) values (57, '34', 57);
insert into backend_location (id, name) values (58, E'Denmark');
insert into backend_areacode (id, code, country_id) values (58, '45', 58);
insert into backend_location (id, name) values (59, E'Djibouti');
insert into backend_areacode (id, code, country_id) values (59, '253', 59);
insert into backend_location (id, name) values (60, E'Dominica');
insert into backend_areacode (id, code, country_id) values (60, '1767', 60);
insert into backend_location (id, name) values (61, E'Dominican Republic');
insert into backend_areacode (id, code, country_id) values (61, '1849', 61);
insert into backend_location (id, name) values (62, E'Dominican Republic');
insert into backend_areacode (id, code, country_id) values (62, '1829', 62);
insert into backend_location (id, name) values (63, E'Dominican Republic');
insert into backend_areacode (id, code, country_id) values (63, '1809', 63);
insert into backend_location (id, name) values (64, E'Ecuador');
insert into backend_areacode (id, code, country_id) values (64, '593', 64);
insert into backend_location (id, name) values (65, E'Egypt');
insert into backend_areacode (id, code, country_id) values (65, '20', 65);
insert into backend_location (id, name) values (66, E'El Salvador');
insert into backend_areacode (id, code, country_id) values (66, '503', 66);
insert into backend_location (id, name) values (67, E'Equatorial Guinea');
insert into backend_areacode (id, code, country_id) values (67, '240', 67);
insert into backend_location (id, name) values (68, E'Eritrea');
insert into backend_areacode (id, code, country_id) values (68, '291', 68);
insert into backend_location (id, name) values (69, E'Estonia');
insert into backend_areacode (id, code, country_id) values (69, '372', 69);
insert into backend_location (id, name) values (70, E'Ethiopia');
insert into backend_areacode (id, code, country_id) values (70, '251', 70);
insert into backend_location (id, name) values (71, E'Falkland Islands (Malvinas)');
insert into backend_areacode (id, code, country_id) values (71, '500', 71);
insert into backend_location (id, name) values (72, E'Faroe Islands');
insert into backend_areacode (id, code, country_id) values (72, '298', 72);
insert into backend_location (id, name) values (73, E'Fiji');
insert into backend_areacode (id, code, country_id) values (73, '679', 73);
insert into backend_location (id, name) values (74, E'Finland');
insert into backend_areacode (id, code, country_id) values (74, '358', 74);
insert into backend_location (id, name) values (75, E'France');
insert into backend_areacode (id, code, country_id) values (75, '33', 75);
insert into backend_location (id, name) values (76, E'French Guiana');
insert into backend_areacode (id, code, country_id) values (76, '594', 76);
insert into backend_location (id, name) values (77, E'French Polynesia');
insert into backend_areacode (id, code, country_id) values (77, '689', 77);
insert into backend_location (id, name) values (78, E'French Southern Territories');
insert into backend_areacode (id, code, country_id) values (78, '262', 78);
insert into backend_location (id, name) values (79, E'Gabon');
insert into backend_areacode (id, code, country_id) values (79, '241', 79);
insert into backend_location (id, name) values (80, E'Gambia');
insert into backend_areacode (id, code, country_id) values (80, '220', 80);
insert into backend_location (id, name) values (81, E'Georgia');
insert into backend_areacode (id, code, country_id) values (81, '995', 81);
insert into backend_location (id, name) values (82, E'Germany');
insert into backend_areacode (id, code, country_id) values (82, '49', 82);
insert into backend_location (id, name) values (83, E'Ghana');
insert into backend_areacode (id, code, country_id) values (83, '233', 83);
insert into backend_location (id, name) values (84, E'Gibraltar');
insert into backend_areacode (id, code, country_id) values (84, '350', 84);
insert into backend_location (id, name) values (85, E'Greece');
insert into backend_areacode (id, code, country_id) values (85, '30', 85);
insert into backend_location (id, name) values (86, E'Greenland');
insert into backend_areacode (id, code, country_id) values (86, '299', 86);
insert into backend_location (id, name) values (87, E'Grenada');
insert into backend_areacode (id, code, country_id) values (87, '1473', 87);
insert into backend_location (id, name) values (88, E'Guadeloupe');
insert into backend_areacode (id, code, country_id) values (88, '590', 88);
insert into backend_location (id, name) values (89, E'Guam');
insert into backend_areacode (id, code, country_id) values (89, '1671', 89);
insert into backend_location (id, name) values (90, E'Guatemala');
insert into backend_areacode (id, code, country_id) values (90, '502', 90);
insert into backend_location (id, name) values (91, E'Guernsey');
insert into backend_areacode (id, code, country_id) values (91, '44', 91);
insert into backend_location (id, name) values (92, E'Guinea');
insert into backend_areacode (id, code, country_id) values (92, '224', 92);
insert into backend_location (id, name) values (93, E'Guinea-Bissau');
insert into backend_areacode (id, code, country_id) values (93, '245', 93);
insert into backend_location (id, name) values (94, E'Guyana');
insert into backend_areacode (id, code, country_id) values (94, '592', 94);
insert into backend_location (id, name) values (95, E'Haiti');
insert into backend_areacode (id, code, country_id) values (95, '509', 95);
insert into backend_location (id, name) values (96, E'Heard & McDonald Islands');
insert into backend_areacode (id, code, country_id) values (96, '672', 96);
insert into backend_location (id, name) values (97, E'Holy See (Vatican City State)');
insert into backend_areacode (id, code, country_id) values (97, '379', 97);
insert into backend_location (id, name) values (98, E'Honduras');
insert into backend_areacode (id, code, country_id) values (98, '504', 98);
insert into backend_location (id, name) values (99, E'Hong Kong');
insert into backend_areacode (id, code, country_id) values (99, '852', 99);
insert into backend_location (id, name) values (100, E'Hungary');
insert into backend_areacode (id, code, country_id) values (100, '36', 100);
insert into backend_location (id, name) values (101, E'Iceland');
insert into backend_areacode (id, code, country_id) values (101, '354', 101);
insert into backend_location (id, name) values (102, E'India');
insert into backend_areacode (id, code, country_id) values (102, '91', 102);
insert into backend_location (id, name) values (103, E'Indonesia');
insert into backend_areacode (id, code, country_id) values (103, '62', 103);
insert into backend_location (id, name) values (104, E'Iran, Islamic Republic of');
insert into backend_areacode (id, code, country_id) values (104, '98', 104);
insert into backend_location (id, name) values (105, E'Iraq');
insert into backend_areacode (id, code, country_id) values (105, '964', 105);
insert into backend_location (id, name) values (106, E'Ireland');
insert into backend_areacode (id, code, country_id) values (106, '353', 106);
insert into backend_location (id, name) values (107, E'Isle of Man');
insert into backend_areacode (id, code, country_id) values (107, '44', 107);
insert into backend_location (id, name) values (108, E'Israel');
insert into backend_areacode (id, code, country_id) values (108, '972', 108);
insert into backend_location (id, name) values (109, E'Italy');
insert into backend_areacode (id, code, country_id) values (109, '39', 109);
insert into backend_location (id, name) values (110, E'Jamaica');
insert into backend_areacode (id, code, country_id) values (110, '1876', 110);
insert into backend_location (id, name) values (111, E'Jamaica');
insert into backend_areacode (id, code, country_id) values (111, '1658', 111);
insert into backend_location (id, name) values (112, E'Japan');
insert into backend_areacode (id, code, country_id) values (112, '81', 112);
insert into backend_location (id, name) values (113, E'Jersey');
insert into backend_areacode (id, code, country_id) values (113, '44', 113);
insert into backend_location (id, name) values (114, E'Jordan');
insert into backend_areacode (id, code, country_id) values (114, '962', 114);
insert into backend_location (id, name) values (115, E'Kazakhstan');
insert into backend_areacode (id, code, country_id) values (115, '77', 115);
insert into backend_location (id, name) values (116, E'Kenya');
insert into backend_areacode (id, code, country_id) values (116, '254', 116);
insert into backend_location (id, name) values (117, E'Kiribati');
insert into backend_areacode (id, code, country_id) values (117, '686', 117);
insert into backend_location (id, name) values (118, E'Korea, Democratic People\'s Republic of');
insert into backend_areacode (id, code, country_id) values (118, '850', 118);
insert into backend_location (id, name) values (119, E'Korea, Republic of');
insert into backend_areacode (id, code, country_id) values (119, '82', 119);
insert into backend_location (id, name) values (120, E'Kuwait');
insert into backend_areacode (id, code, country_id) values (120, '965', 120);
insert into backend_location (id, name) values (121, E'Kyrgyzstan');
insert into backend_areacode (id, code, country_id) values (121, '996', 121);
insert into backend_location (id, name) values (122, E'Kosovo');
insert into backend_areacode (id, code, country_id) values (122, '383', 122);
insert into backend_location (id, name) values (123, E'Lao People\'s Democratic Republic');
insert into backend_areacode (id, code, country_id) values (123, '856', 123);
insert into backend_location (id, name) values (124, E'Latvia');
insert into backend_areacode (id, code, country_id) values (124, '371', 124);
insert into backend_location (id, name) values (125, E'Lebanon');
insert into backend_areacode (id, code, country_id) values (125, '961', 125);
insert into backend_location (id, name) values (126, E'Lesotho');
insert into backend_areacode (id, code, country_id) values (126, '266', 126);
insert into backend_location (id, name) values (127, E'Liberia');
insert into backend_areacode (id, code, country_id) values (127, '231', 127);
insert into backend_location (id, name) values (128, E'Libyan Arab Jamahiriya');
insert into backend_areacode (id, code, country_id) values (128, '218', 128);
insert into backend_location (id, name) values (129, E'Liechtenstein');
insert into backend_areacode (id, code, country_id) values (129, '423', 129);
insert into backend_location (id, name) values (130, E'Lithuania');
insert into backend_areacode (id, code, country_id) values (130, '370', 130);
insert into backend_location (id, name) values (131, E'Luxembourg');
insert into backend_areacode (id, code, country_id) values (131, '352', 131);
insert into backend_location (id, name) values (132, E'Macao');
insert into backend_areacode (id, code, country_id) values (132, '853', 132);
insert into backend_location (id, name) values (133, E'Macedonia, The Former Yugoslav Republic of');
insert into backend_areacode (id, code, country_id) values (133, '389', 133);
insert into backend_location (id, name) values (134, E'Madagascar');
insert into backend_areacode (id, code, country_id) values (134, '261', 134);
insert into backend_location (id, name) values (135, E'Malawi');
insert into backend_areacode (id, code, country_id) values (135, '265', 135);
insert into backend_location (id, name) values (136, E'Malaysia');
insert into backend_areacode (id, code, country_id) values (136, '60', 136);
insert into backend_location (id, name) values (137, E'Maldives');
insert into backend_areacode (id, code, country_id) values (137, '960', 137);
insert into backend_location (id, name) values (138, E'Mali');
insert into backend_areacode (id, code, country_id) values (138, '223', 138);
insert into backend_location (id, name) values (139, E'Malta');
insert into backend_areacode (id, code, country_id) values (139, '356', 139);
insert into backend_location (id, name) values (140, E'Marshall Islands');
insert into backend_areacode (id, code, country_id) values (140, '692', 140);
insert into backend_location (id, name) values (141, E'Martinique');
insert into backend_areacode (id, code, country_id) values (141, '596', 141);
insert into backend_location (id, name) values (142, E'Mauritania');
insert into backend_areacode (id, code, country_id) values (142, '222', 142);
insert into backend_location (id, name) values (143, E'Mauritius');
insert into backend_areacode (id, code, country_id) values (143, '230', 143);
insert into backend_location (id, name) values (144, E'Mayotte');
insert into backend_areacode (id, code, country_id) values (144, '262', 144);
insert into backend_location (id, name) values (145, E'Mexico');
insert into backend_areacode (id, code, country_id) values (145, '52', 145);
insert into backend_location (id, name) values (146, E'Micronesia, Federated States of');
insert into backend_areacode (id, code, country_id) values (146, '691', 146);
insert into backend_location (id, name) values (147, E'Moldova, Republic of');
insert into backend_areacode (id, code, country_id) values (147, '373', 147);
insert into backend_location (id, name) values (148, E'Monaco');
insert into backend_areacode (id, code, country_id) values (148, '377', 148);
insert into backend_location (id, name) values (149, E'Mongolia');
insert into backend_areacode (id, code, country_id) values (149, '976', 149);
insert into backend_location (id, name) values (150, E'Montenegro');
insert into backend_areacode (id, code, country_id) values (150, '382', 150);
insert into backend_location (id, name) values (151, E'Montserrat');
insert into backend_areacode (id, code, country_id) values (151, '1664', 151);
insert into backend_location (id, name) values (152, E'Morocco');
insert into backend_areacode (id, code, country_id) values (152, '212', 152);
insert into backend_location (id, name) values (153, E'Mozambique');
insert into backend_areacode (id, code, country_id) values (153, '258', 153);
insert into backend_location (id, name) values (154, E'Myanmar');
insert into backend_areacode (id, code, country_id) values (154, '95', 154);
insert into backend_location (id, name) values (155, E'Namibia');
insert into backend_areacode (id, code, country_id) values (155, '264', 155);
insert into backend_location (id, name) values (156, E'Nauru');
insert into backend_areacode (id, code, country_id) values (156, '674', 156);
insert into backend_location (id, name) values (157, E'Nepal');
insert into backend_areacode (id, code, country_id) values (157, '977', 157);
insert into backend_location (id, name) values (158, E'Netherlands');
insert into backend_areacode (id, code, country_id) values (158, '31', 158);
insert into backend_location (id, name) values (159, E'Caribbean Netherlands');
insert into backend_areacode (id, code, country_id) values (159, '599', 159);
insert into backend_location (id, name) values (160, E'New Caledonia');
insert into backend_areacode (id, code, country_id) values (160, '687', 160);
insert into backend_location (id, name) values (161, E'New Zealand');
insert into backend_areacode (id, code, country_id) values (161, '64', 161);
insert into backend_location (id, name) values (162, E'Nicaragua');
insert into backend_areacode (id, code, country_id) values (162, '505', 162);
insert into backend_location (id, name) values (163, E'Niger');
insert into backend_areacode (id, code, country_id) values (163, '227', 163);
insert into backend_location (id, name) values (164, E'Nigeria');
insert into backend_areacode (id, code, country_id) values (164, '234', 164);
insert into backend_location (id, name) values (165, E'Niue');
insert into backend_areacode (id, code, country_id) values (165, '683', 165);
insert into backend_location (id, name) values (166, E'Norfolk Island');
insert into backend_areacode (id, code, country_id) values (166, '672', 166);
insert into backend_location (id, name) values (167, E'Northern Mariana Islands');
insert into backend_areacode (id, code, country_id) values (167, '1670', 167);
insert into backend_location (id, name) values (168, E'Norway');
insert into backend_areacode (id, code, country_id) values (168, '47', 168);
insert into backend_location (id, name) values (169, E'Oman');
insert into backend_areacode (id, code, country_id) values (169, '968', 169);
insert into backend_location (id, name) values (170, E'Pakistan');
insert into backend_areacode (id, code, country_id) values (170, '92', 170);
insert into backend_location (id, name) values (171, E'Palau');
insert into backend_areacode (id, code, country_id) values (171, '680', 171);
insert into backend_location (id, name) values (172, E'Palestinian Territory, Occupied');
insert into backend_areacode (id, code, country_id) values (172, '970', 172);
insert into backend_location (id, name) values (173, E'Panama');
insert into backend_areacode (id, code, country_id) values (173, '507', 173);
insert into backend_location (id, name) values (174, E'Papua New Guinea');
insert into backend_areacode (id, code, country_id) values (174, '675', 174);
insert into backend_location (id, name) values (175, E'Paraguay');
insert into backend_areacode (id, code, country_id) values (175, '595', 175);
insert into backend_location (id, name) values (176, E'Peru');
insert into backend_areacode (id, code, country_id) values (176, '51', 176);
insert into backend_location (id, name) values (177, E'Philippines');
insert into backend_areacode (id, code, country_id) values (177, '63', 177);
insert into backend_location (id, name) values (178, E'Pitcairn');
insert into backend_areacode (id, code, country_id) values (178, '872', 178);
insert into backend_location (id, name) values (179, E'Poland');
insert into backend_areacode (id, code, country_id) values (179, '48', 179);
insert into backend_location (id, name) values (180, E'Portugal');
insert into backend_areacode (id, code, country_id) values (180, '351', 180);
insert into backend_location (id, name) values (181, E'Puerto Rico');
insert into backend_areacode (id, code, country_id) values (181, '1939', 181);
insert into backend_location (id, name) values (182, E'Puerto Rico');
insert into backend_areacode (id, code, country_id) values (182, '1787', 182);
insert into backend_location (id, name) values (183, E'Qatar');
insert into backend_areacode (id, code, country_id) values (183, '974', 183);
insert into backend_location (id, name) values (184, E'Romania');
insert into backend_areacode (id, code, country_id) values (184, '40', 184);
insert into backend_location (id, name) values (185, E'Russia');
insert into backend_areacode (id, code, country_id) values (185, '7', 185);
insert into backend_location (id, name) values (186, E'Rwanda');
insert into backend_areacode (id, code, country_id) values (186, '250', 186);
insert into backend_location (id, name) values (187, E'Réunion');
insert into backend_areacode (id, code, country_id) values (187, '262', 187);
insert into backend_location (id, name) values (188, E'Saint Barthélemy');
insert into backend_areacode (id, code, country_id) values (188, '590', 188);
insert into backend_location (id, name) values (189, E'Saint Helena, Ascension and Tristan Da Cunha');
insert into backend_areacode (id, code, country_id) values (189, '290', 189);
insert into backend_location (id, name) values (190, E'Saint Kitts and Nevis');
insert into backend_areacode (id, code, country_id) values (190, '1869', 190);
insert into backend_location (id, name) values (191, E'Saint Lucia');
insert into backend_areacode (id, code, country_id) values (191, '1758', 191);
insert into backend_location (id, name) values (192, E'Saint Martin');
insert into backend_areacode (id, code, country_id) values (192, '590', 192);
insert into backend_location (id, name) values (193, E'Saint Pierre and Miquelon');
insert into backend_areacode (id, code, country_id) values (193, '508', 193);
insert into backend_location (id, name) values (194, E'Saint Vincent and the Grenadines');
insert into backend_areacode (id, code, country_id) values (194, '1784', 194);
insert into backend_location (id, name) values (195, E'Samoa');
insert into backend_areacode (id, code, country_id) values (195, '685', 195);
insert into backend_location (id, name) values (196, E'San Marino');
insert into backend_areacode (id, code, country_id) values (196, '378', 196);
insert into backend_location (id, name) values (197, E'Sao Tome and Principe');
insert into backend_areacode (id, code, country_id) values (197, '239', 197);
insert into backend_location (id, name) values (198, E'Saudi Arabia');
insert into backend_areacode (id, code, country_id) values (198, '966', 198);
insert into backend_location (id, name) values (199, E'Senegal');
insert into backend_areacode (id, code, country_id) values (199, '221', 199);
insert into backend_location (id, name) values (200, E'Serbia');
insert into backend_areacode (id, code, country_id) values (200, '381', 200);
insert into backend_location (id, name) values (201, E'Seychelles');
insert into backend_areacode (id, code, country_id) values (201, '248', 201);
insert into backend_location (id, name) values (202, E'Sierra Leone');
insert into backend_areacode (id, code, country_id) values (202, '232', 202);
insert into backend_location (id, name) values (203, E'Singapore');
insert into backend_areacode (id, code, country_id) values (203, '65', 203);
insert into backend_location (id, name) values (204, E'Slovakia');
insert into backend_areacode (id, code, country_id) values (204, '421', 204);
insert into backend_location (id, name) values (205, E'Slovenia');
insert into backend_areacode (id, code, country_id) values (205, '386', 205);
insert into backend_location (id, name) values (206, E'Solomon Islands');
insert into backend_areacode (id, code, country_id) values (206, '677', 206);
insert into backend_location (id, name) values (207, E'Somalia');
insert into backend_areacode (id, code, country_id) values (207, '252', 207);
insert into backend_location (id, name) values (208, E'South Africa');
insert into backend_areacode (id, code, country_id) values (208, '27', 208);
insert into backend_location (id, name) values (209, E'South Georgia and the South Sandwich Islands');
insert into backend_areacode (id, code, country_id) values (209, '500', 209);
insert into backend_location (id, name) values (210, E'Spain');
insert into backend_areacode (id, code, country_id) values (210, '34', 210);
insert into backend_location (id, name) values (211, E'Sri Lanka');
insert into backend_areacode (id, code, country_id) values (211, '94', 211);
insert into backend_location (id, name) values (212, E'Sudan');
insert into backend_areacode (id, code, country_id) values (212, '249', 212);
insert into backend_location (id, name) values (213, E'South Sudan');
insert into backend_areacode (id, code, country_id) values (213, '211', 213);
insert into backend_location (id, name) values (214, E'Suriname');
insert into backend_areacode (id, code, country_id) values (214, '597', 214);
insert into backend_location (id, name) values (215, E'Svalbard and Jan Mayen');
insert into backend_areacode (id, code, country_id) values (215, '47', 215);
insert into backend_location (id, name) values (216, E'Swaziland');
insert into backend_areacode (id, code, country_id) values (216, '268', 216);
insert into backend_location (id, name) values (217, E'Sweden');
insert into backend_areacode (id, code, country_id) values (217, '46', 217);
insert into backend_location (id, name) values (218, E'Switzerland');
insert into backend_areacode (id, code, country_id) values (218, '41', 218);
insert into backend_location (id, name) values (219, E'Syrian Arab Republic');
insert into backend_areacode (id, code, country_id) values (219, '963', 219);
insert into backend_location (id, name) values (220, E'Sint Maarten');
insert into backend_areacode (id, code, country_id) values (220, '721', 220);
insert into backend_location (id, name) values (221, E'Taiwan, Province of China');
insert into backend_areacode (id, code, country_id) values (221, '886', 221);
insert into backend_location (id, name) values (222, E'Tajikistan');
insert into backend_areacode (id, code, country_id) values (222, '992', 222);
insert into backend_location (id, name) values (223, E'Tanzania, United Republic of');
insert into backend_areacode (id, code, country_id) values (223, '255', 223);
insert into backend_location (id, name) values (224, E'Thailand');
insert into backend_areacode (id, code, country_id) values (224, '66', 224);
insert into backend_location (id, name) values (225, E'Timor-Leste');
insert into backend_areacode (id, code, country_id) values (225, '670', 225);
insert into backend_location (id, name) values (226, E'Togo');
insert into backend_areacode (id, code, country_id) values (226, '228', 226);
insert into backend_location (id, name) values (227, E'Tokelau');
insert into backend_areacode (id, code, country_id) values (227, '690', 227);
insert into backend_location (id, name) values (228, E'Tonga');
insert into backend_areacode (id, code, country_id) values (228, '676', 228);
insert into backend_location (id, name) values (229, E'Trinidad and Tobago');
insert into backend_areacode (id, code, country_id) values (229, '1868', 229);
insert into backend_location (id, name) values (230, E'Tunisia');
insert into backend_areacode (id, code, country_id) values (230, '216', 230);
insert into backend_location (id, name) values (231, E'Turkey');
insert into backend_areacode (id, code, country_id) values (231, '90', 231);
insert into backend_location (id, name) values (232, E'Turkmenistan');
insert into backend_areacode (id, code, country_id) values (232, '993', 232);
insert into backend_location (id, name) values (233, E'Turks and Caicos Islands');
insert into backend_areacode (id, code, country_id) values (233, '1649', 233);
insert into backend_location (id, name) values (234, E'Tuvalu');
insert into backend_areacode (id, code, country_id) values (234, '688', 234);
insert into backend_location (id, name) values (235, E'Uganda');
insert into backend_areacode (id, code, country_id) values (235, '256', 235);
insert into backend_location (id, name) values (236, E'Ukraine');
insert into backend_areacode (id, code, country_id) values (236, '380', 236);
insert into backend_location (id, name) values (237, E'United Arab Emirates');
insert into backend_areacode (id, code, country_id) values (237, '971', 237);
insert into backend_location (id, name) values (238, E'United Kingdom');
insert into backend_areacode (id, code, country_id) values (238, '44', 238);
insert into backend_location (id, name) values (239, E'United States');
insert into backend_areacode (id, code, country_id) values (239, '1', 239);
insert into backend_location (id, name) values (240, E'Uruguay');
insert into backend_areacode (id, code, country_id) values (240, '598', 240);
insert into backend_location (id, name) values (241, E'Uzbekistan');
insert into backend_areacode (id, code, country_id) values (241, '998', 241);
insert into backend_location (id, name) values (242, E'Vanuatu');
insert into backend_areacode (id, code, country_id) values (242, '678', 242);
insert into backend_location (id, name) values (243, E'Venezuela, Bolivarian Republic of');
insert into backend_areacode (id, code, country_id) values (243, '58', 243);
insert into backend_location (id, name) values (244, E'Viet Nam');
insert into backend_areacode (id, code, country_id) values (244, '84', 244);
insert into backend_location (id, name) values (245, E'Virgin Islands, British');
insert into backend_areacode (id, code, country_id) values (245, '1284', 245);
insert into backend_location (id, name) values (246, E'Virgin Islands, U.S.');
insert into backend_areacode (id, code, country_id) values (246, '1340', 246);
insert into backend_location (id, name) values (247, E'Wallis and Futuna');
insert into backend_areacode (id, code, country_id) values (247, '681', 247);
insert into backend_location (id, name) values (248, E'Western Sarah');
insert into backend_areacode (id, code, country_id) values (248, '212', 248);
insert into backend_location (id, name) values (249, E'Yemen');
insert into backend_areacode (id, code, country_id) values (249, '967', 249);
insert into backend_location (id, name) values (250, E'Zambia');
insert into backend_areacode (id, code, country_id) values (250, '260', 250);
insert into backend_location (id, name) values (251, E'Zimbabwe');
insert into backend_areacode (id, code, country_id) values (251, '263', 251);
insert into backend_location (id, name) values (252, E'Åland Islands');
insert into backend_areacode (id, code, country_id) values (252, '358', 252);