# Generated by Django 3.1.14 on 2023-10-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20231008_1208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('requester', 'requestee')},
        ),
    ]
