# Generated by Django 3.1.14 on 2023-10-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20231008_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='travelinfo',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
