# Generated by Django 3.1.14 on 2023-10-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20231016_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Greg', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='area_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.areacode'),
            preserve_default=False,
        ),
    ]
