# Generated by Django 3.1.14 on 2023-10-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20231020_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='name',
        ),
    ]
