# Generated by Django 3.1.14 on 2023-10-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20231020_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
