# Generated by Django 3.1.14 on 2023-10-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20231023_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_id',
            field=models.CharField(default='lol', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areacode',
            name='country',
            field=models.CharField(max_length=128),
        ),
    ]
