# Generated by Django 3.1.14 on 2023-10-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20231025_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='state',
        ),
    ]
