# Generated by Django 3.1.14 on 2024-11-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20231114_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_type',
            field=models.IntegerField(choices=[(0, 'GRAVATAR'), (1, 'FILE'), (2, 'BEAN')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
