# Generated by Django 3.1.14 on 2024-11-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20241101_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='close_friend_perms',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_perms',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
