# Generated by Django 3.1.14 on 2024-11-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20241103_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proximity_algorithm',
            field=models.IntegerField(choices=[(0, 'SMART'), (1, 'REGION'), (2, 'DISTANCE')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='proximity_distance',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
