# Generated by Django 3.1.14 on 2024-11-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20241103_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='close_friend_perms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend_perms',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_discord',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_instagram',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_see_exact_location',
            field=models.IntegerField(choices=[(0, 'FRIENDS'), (1, 'CLOSE_FRIENDS'), (2, 'NOBODY')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_see_full_schedule',
            field=models.IntegerField(choices=[(0, 'FRIENDS'), (1, 'CLOSE_FRIENDS'), (2, 'NOBODY')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_view_contact_info',
            field=models.IntegerField(choices=[(0, 'FRIENDS'), (1, 'CLOSE_FRIENDS'), (2, 'NOBODY')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_view_email',
            field=models.IntegerField(choices=[(0, 'FRIENDS'), (1, 'CLOSE_FRIENDS'), (2, 'NOBODY')], default=2),
        ),
    ]
