# Generated by Django 3.1.14 on 2025-01-15 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20241118_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='close_friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
